CREATE TABLE Addresses (
	address		TEXT	NOT NULL	UNIQUE,
	label		TEXT	NOT NULL,
	change		INTEGER	NOT NULL,
	n			INTEGER NOT NULL,

	PRIMARY KEY (address)
);

CREATE TABLE Data (
	Key		TEXT	NOT NULL	UNIQUE,
	Value	TEXT	NOT NULL
);