CREATE TABLE Addresses (
	address		TEXT	NOT NULL	UNIQUE,
	label		TEXT	NOT NULL,
	change		INTEGER	NOT NULL,
	n			INTEGER NOT NULL,

	PRIMARY KEY (address)
);

CREATE TABLE UTXOs (
	txid		TEXT	NOT NULL,
	vout		INTEGER	NOT NULL,
	satoshis	INTEGER	NOT NULL,
	height		INTEGER NOT NULL,
	script		TEXT	NOT NULL,
    address     TEXT	NOT NULL,
	path		TEXT	NOT NULL,

	PRIMARY KEY (txid, vout)
);

CREATE TABLE Data (
	Key		TEXT	NOT NULL	UNIQUE,
	Value	TEXT	NOT NULL
);